server:
  port: 8080

github:
  Client:
    id: 652b8dbccd3e544616e8
    secret: 26202588fd5fdd4fe9f8909f389823c58dfe39be
  Redirect:
    uri: http://localhost:8080/callback
spring:
  datasource:
    url: jdbc:mysql://39.106.163.180:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Abc331433
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true